import { Category } from '../app/core/models/api/category.model';
import { Product } from '../app/core/models/api/product.model';
import { TableItem } from '../app/core/models/api/table-item.model';
import { Table } from '../app/core/models/api/table.model';

const categories: Category[] = [
  {
    id: 1,
    name: 'Beverages',
    description: 'Refreshing drinks',
    image: null,
    organizationID: 1,
  },
  {
    id: 2,
    name: 'Desserts',
    description: 'Sweet treats',
    image: null,
    organizationID: 1,
  },
  {
    id: 3,
    name: 'Main Courses',
    description: 'Hearty meals',
    image: null,
    organizationID: 1,
  },
];

const products: Product[] = [
  {
    id: 1,
    code: '1010',
    name: 'Espresso',
    price: 2.5,
    description: 'Strong black coffee',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
  {
    id: 2,
    code: '1515',
    name: 'Cheesecake',
    price: 5.0,
    description: 'Classic New York cheesecake',
    image: null,
    categoryID: 2,
    organizationID: 1,
  },
  {
    id: 3,
    code: '1234',
    name: 'Cappuccino',
    price: 3.0,
    description: 'Espresso with steamed milk and foam',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
  {
    id: 4,
    code: '5323',
    name: 'Latte',
    price: 3.5,
    description: 'Smooth espresso with steamed milk',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
  {
    id: 5,
    code: '1011',
    name: 'Brownie',
    price: 4.0,
    description: 'Chocolate fudge brownie',
    image: null,
    categoryID: 2,
    organizationID: 1,
  },
  {
    id: 6,
    code: '3412',
    name: 'Burger',
    price: 8.0,
    description: 'Juicy beef burger with fresh toppings',
    image: null,
    categoryID: 3,
    organizationID: 1,
  },
  {
    id: 7,
    code: '1521',
    name: 'Pizza Margherita',
    price: 10.0,
    description: 'Classic Margherita pizza with fresh basil',
    image: null,
    categoryID: 3,
    organizationID: 1,
  },
  {
    id: 10,
    code: '1510',
    name: 'Peach Tea',
    price: 2.5,
    description: 'Peach Tea',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
  {
    id: 8,
    code: '19110',
    name: 'Turkish Coffee',
    price: 2.5,
    description: 'Strong turkish coffee',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
  {
    id: 9,
    code: '1310',
    name: 'Milkshake',
    price: 2.5,
    description: 'Strong black coffee',
    image: null,
    categoryID: 1,
    organizationID: 1,
  },
];

const tables: Table[] = [
  {
    id: 1,
    code: 'T01',
    status: 'Occupied',
    totalPrice: 7.5,
    locationID: 1,
    staffUserID: 1,
  },
  {
    id: 2,
    code: 'T02',
    status: 'Available',
    totalPrice: 0,
    locationID: 1,
    staffUserID: 2,
  },
  {
    id: 3,
    code: 'T03',
    status: 'Occupied',
    totalPrice: 15.0,
    locationID: 1,
    staffUserID: 3,
  },
  {
    id: 4,
    code: 'T04',
    status: 'Available',
    totalPrice: 20.0,
    locationID: 2,
    staffUserID: 4,
  },
];

const tableItems: TableItem[] = [
  {
    id: 1,
    tableID: 1,
    product: {
      id: 1,
      code: '1010',
      name: 'Espresso',
      price: 2.5,
      description: 'Strong black coffee',
      image: null,
      categoryID: 1,
      organizationID: 1,
    },
    locationID: 1,
    quantity: 2,
    totalPrice: 5.0,
  },
  {
    id: 2,
    tableID: 1,
    product: {
      id: 2,
      code: '1515',
      name: 'Cheesecake',
      price: 5.0,
      description: 'Classic New York cheesecake',
      image: null,
      categoryID: 2,
      organizationID: 1,
    },
    locationID: 1,
    quantity: 1,
    totalPrice: 5.0,
  },
  {
    id: 3,
    tableID: 3,
    product: {
      id: 6,
      code: '3412',
      name: 'Burger',
      price: 8.0,
      description: 'Juicy beef burger with fresh toppings',
      image: null,
      categoryID: 3,
      organizationID: 1,
    },
    locationID: 1,
    quantity: 1,
    totalPrice: 8.0,
  },
  {
    id: 4,
    tableID: 3,
    product: {
      id: 7,
      code: '1521',
      name: 'Pizza Margherita',
      price: 10.0,
      description: 'Classic Margherita pizza with fresh basil',
      image: null,
      categoryID: 3,
      organizationID: 1,
    },
    locationID: 1,
    quantity: 1,
    totalPrice: 10.0,
  },
  {
    id: 5,
    tableID: 4,
    product: {
      id: 3,
      code: '1234',
      name: 'Cappuccino',
      price: 3.0,
      description: 'Espresso with steamed milk and foam',
      image: null,
      categoryID: 1,
      organizationID: 1,
    },
    locationID: 2,
    quantity: 2,
    totalPrice: 6.0,
  },
];

export { categories, products, tables, tableItems };
